# Generated by Django 5.1.1 on 2026-03-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_sessions', '0002_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
